export const GET_MY_FAVORITES_PENDING = "GET_MY_FAVORITES_PENDING";
export const GET_MY_FAVORITES_REJECTED = "GET_MY_FAVORITES_REJECTED";
export const GET_MY_FAVORITES_SUCCESS = "GET_MY_FAVORITES_SUCCESS";

export const ADD_TO_FAVORITES_PENDING = "ADD_TO_FAVORITES_PENDING";
export const ADD_TO_FAVORITES_REJECTED = "ADD_TO_FAVORITES_REJECTED";
export const ADD_TO_FAVORITES_SUCCESS = "ADD_TO_FAVORITES_SUCCESS";

export const REMOVE_FROM_FAVORITES_PENDING = "REMOVE_FROM_FAVORITES_PENDING";
export const REMOVE_FROM_FAVORITES_REJECTED = "REMOVE_FROM_FAVORITES_REJECTED";
export const REMOVE_FROM_FAVORITES_SUCCESS = "REMOVE_FROM_FAVORITES_SUCCESS";
