export const GET_NEARBY_PROPERTIES_PENDING = "GET_NEARBY_PROPERTIES_PENDING";
export const GET_NEARBY_PROPERTIES_SUCCESS = "GET_NEARBY_PROPERTIES_SUCCESS";
export const GET_NEARBY_PROPERTIES_REJECTED = "GET_NEARBY_PROPERTIES_REJECTED";
