
export const GET_POPULAR_PROPERTIES_PENDING = "GET_POPULAR_PROPERTIES_PENDING"
export const GET_POPULAR_PROPERTIES_REJECTED = "GET_POPULAR_PROPERTIES_REJECTED"
export const GET_POPULAR_PROPERTIES_SUCCESS = "GET_POPULAR_PROPERTIES_SUCCESS"

