export const REGISTER_USER_PENDING="REGISTER_USER_PENDING"
export const REGISTER_USER_REJECTED="REGISTER_USER_REJECTED"
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS"

export const LOGIN_USER_PENDING="LOGIN_USER_PENDING"
export const LOGIN_USER_REJECTED="LOGIN_USER_REJECTED"
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS"