export const GET_ALL_RENTS_PENDING = "GET_ALL_RENTS_PENDING";
export const GET_ALL_RENTS_SUCCESS = "GET_ALL_RENTS_SUCCESS";
export const GET_ALL_RENTS_REJECTED = "GET_ALL_RENTS_REJECTED";

export const CONFIRM_RENT_PENDING = "CONFIRM_RENT_PENDING";
export const CONFIRM_RENT_SUCCESS = "CONFIRM_RENT_SUCCESS";
export const CONFIRM_RENT_REJECTED = "CONFIRM_RENT_REJECTED";

export const EDIT_RENT_PENDING = "EDIT_RENT_PENDING";
export const EDIT_RENT_SUCCESS = "EDIT_RENT_SUCCESS";
export const EDIT_RENT_REJECTED = "EDIT_RENT_REJECTED";

export const CANCEL_RENT_PENDING = "CANCEL_RENT_PENDING";
export const CANCEL_RENT_SUCCESS = "CANCEL_RENT_SUCCESS";
export const CANCEL_RENT_REJECTED = "CANCEL_RENT_REJECTED";


