export const GET_USER_DATA_PENDING="GET_USER_DATA_PENDING"
export const GET_USER_DATA_REJECTED="GET_USER_DATA_REJECTED"
export const GET_USER_DATA_SUCCESS="GET_USER_DATA_SUCCESS"

export const EDIT_USER_DATA_PENDING="EDIT_USER_DATA_PENDING"
export const EDIT_USER_DATA_REJECTED="EDIT_USER_DATA_REJECTED"
export const EDIT_USER_DATA_SUCCESS="EDIT_USER_DATA_REJECTED"

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"