GET localhost:3009
Content-Type: application/json

POST localhost:3009/api/v1/auth/register
Content-Type: application/json

{
    "firstName":"gean",
    "lastName":"franco",
    "email":"gean120@gmail.com",
    "password":"root"
}

POST localhost:3009/api/v1/auth/login
Content-Type: application/json

{
    "email":"gean120@gmail.com",
    "password":"root"
}

PATCH localhost:3009/api/v1/auth/forgot_password
Content-Type: application/json

{
    "email":"fran@example.com",
    "password":"root2"
}

POST localhost:3009/api/v1/property/me
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjMmM0NjlhLWI2OTktNDVjOC1iNWFlLWVlMzYyNjM1NzczYyIsImVtYWlsIjoiZ2VhbjEyMEBnbWFpbC5jb20iLCJyb2xlIjoibm9ybWFsIiwiaWF0IjoxNjcwMzYwNzMzfQ.d3hyAKbU7BXlke4VcQ3jczuDjG4ctlDJ429fZhiZqB0
Content-Type: application/json

{
    "title":"Casa con piscina",
    "address":"San Francisco ay10",
    "lat":"102",
    "lon":"25",
    "purpose":"De vacacione",
    "price":"1000",
    "product":"none",
    "category":"Hot",
    "rentFrequency":"si",
    "rooms":"5",
    "baths":"2",
    "area":"303.5",
    "contactName":"admin"
}

GET localhost:3009/api/v1/property/me
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4NDlmNWM1LWY2ZDYtNDE5OC04OWNkLWFiOWUyNTllOGIwZiIsImVtYWlsIjoiZ2VhbngxMjBAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY5OTMxODQ3fQ.HHrCt4DKcL1MYfcc1AmCLWdqX2e9k-nzHDKkXZjWYeU
Content-Type: application/json

GET localhost:3009/api/v1/property/
Content-Type: application/json

GET localhost:3009/api/v1/property/a9f41c88-3d2c-4f06-b57f-f0d72d8b5736
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJhNTgyYjAzLTMyODAtNGMwMy04ODc5LTRlYzg1YmI3ODliMiIsImVtYWlsIjoiZ2VhbkBleGFtcGxlLmNvbSIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2Njk3NTcyMDV9.j-V5vWRkAMgqSAqZDVc7MkAUA6ly1mYJypo_1jPVOeU
Content-Type: application/json

POST localhost:3009/api/v1/property/image/a9f41c88-3d2c-4f06-b57f-f0d72d8b5736
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4NDlmNWM1LWY2ZDYtNDE5OC04OWNkLWFiOWUyNTllOGIwZiIsImVtYWlsIjoiZ2VhbngxMjBAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY5OTMxODQ3fQ.HHrCt4DKcL1MYfcc1AmCLWdqX2e9k-nzHDKkXZjWYeU
Content-Type: application/json

POST localhost:3009/api/v1/bank-account
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIyMGQ1ODZiLTAwY2QtNDIwNS1iMmZlLWQ0NzUxMTAwMmJhOCIsImVtYWlsIjoiZ2VhbkBleGFtcGxlLmNvbSIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2NjkxNzkzMzZ9.xr4FjfH-MlGqySq1LDlvAAbSvyXWP9pX6Ykj_4YS-tI
Content-Type: application/json

{
    "numberAccount":"4557805845457",
    "expired":"2023",
    "found":"100",
    "cvv":"421"
}

GET localhost:3009/api/v1/order
authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiZTRmMTA5LTMxOTQtNDg1OS1iYmQzLWVhNzc4YTQyNmYwOCIsImVtYWlsIjoiZ2VhbjEyMEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzAwMzY5MTF9.JLORjavIuJdd9qN0D199BdAFSQAuiWrVV0Js7bzb6uQ
content-type: application/json

POST localhost:3009/api/v1/order/buy/3839004
authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjMmM0NjlhLWI2OTktNDVjOC1iNWFlLWVlMzYyNjM1NzczYyIsImVtYWlsIjoiZ2VhbjEyMEBnbWFpbC5jb20iLCJyb2xlIjoibm9ybWFsIiwiaWF0IjoxNjcwMzYzMDAxfQ.MK7rZD4Ia0gz-kR3up_PvV6AalGk8Na00woHzzE8oOM
content-type: application/json

{
    "total": 1
}

